title: Github site
author: Jayden Humphrey
email: ggggg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A great site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
